server:
  port: 9098
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/ies_dev
    username: root
    password: abcd
    driver-class-name: com.mysql.cj.jdbc.Driver  jpa:    properties:      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: update  mail:    host: gmail.smtp.com
    port: 587
    username: bakthulaupendra1@gmail.com 
    password: lakshita@6
    properties:      mail:
        smtp:
          starttls:
            enable: true
          auth: true  
app:
  messages:
    unlockSuccess: Your Account Unlocked Successfully.
    unlockFail: Failed To Unlock Account.
    accountLocked: Your Account Is Locked.
    invalidCredential: Invalid Credentials
    regEmailSub: User Registration Successfull
    forgotPswdEmailSub: Forgot Password
    forgotPswdSuccess: Email Sent With Password
    forgotPswdFail: Enter Correct Email Id
    regEmailBodyFile: UNLOCK-ACC-EMAIL-BODY.txt
    forgotPswdEmailBodyFile: PASSWORD-RECOVER-EMAIL-BODY.txt
    
           
       
      
  